json_format : |
  {
    "genes": [
         "<name of gene>",
         "<name of gene>",
         ...
    ]
  }
none_return : |
  {
    "genes": [
         "None"
    ]
  }
example_genes: |
  {
    "genes": [
      "APOE",
      "BRCA1",
      "TP53",
      "EGFR",
      "ALK",
      "HER2",
      "KRAS",
      "PTEN",
      "BRAF",
      "RET",
      "CDKN2A",
      "KIT",
      "ERBB2",
      "PIK3CA",
      "ALK",
      "EGFR",
      "TERT",
      "RB1",
      "FLT3",
      "MAPK1",
      "MET",
      "STK11",
      "NF1",
      "CDH1",
      "ATM",
      "PTEN",
      "VHL",
      "NOTCH1",
      "JAK2",
      "BIRC3",
      "ALK",
      "AKT1",
      "KRAS",
      "MYC",
      "BRCA2",
      "EGFR",
      "FGFR1",
      "FGFR2",
      "FGFR3",
      "FANCA",
      "AR",
      "TSC1",
      "TSC2",
      "SMAD4",
      "RB1",
      "CDKN2B",
      "CDKN2C",
      "MAX",
      "MEN1",
      "SDHB",
      "SDHC",
      "SDHD",
      "CDK4",
      "CDKN2A",
      "GNA11",
      "GNAQ",
      "CTNNB1",
      "BRAF",
      "NRAS",
      "HRAS",
      "KIT",
      "KITLG",
      "PTPN11",
      "FLT3",
      "KRAS",
      "NPM1",
      "IDH1",
      "IDH2",
      "KMT2A",
      "WT1",
      "CBL",
      "STAG2",
      "SRSF2",
      "SF3B1",
      "U2AF1",
      "TP53",
      "RUNX1",
      "ASXL1",
      "DNMT3A",
      "TET2",
      "ETV6",
      "PTPN11",
      "FLT3",
      "NRAS",
      "KRAS",
      "CBL",
      "JAK2",
      "NPM1",
      "IDH1",
      "IDH2",
      "DNMT3A",
      "HRAS",
      "SF3B1",
      "SRSF2",
      "TERT"
    ]
  }
